import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <a href={"https://www.facebook.com/BozemanCommunityKiln"} rel="noopener noreferrer" target={"_blank"}>
                            <Image src={"https://media.graphcms.com/8KDmAb7aTjGw6RsxKkIa"} alt={"Follow on Facebook"} width={"40px"} height={"40px"}/>
                        </a>
        <a href={"https://www.instagram.com/bckiln/"} rel="noopener noreferrer" target={"_blank"}>
                            <Image src={"https://media.graphcms.com/pOsoM4xoSNiGPWq5d1Jg"} alt={"Follow on Instagram"} width={"40px"} height={"40px"}/>
                        </a>
      </main>
    </div>
  )
}
